Repository upe-garanhuns/pweb-2023.2-laravel, pull requests merged in 2024-03, with the labels that each got.

#2 docs: tradução do template de Issues
  docs/issue_template.md
Labels: documentation

#12 Conectar com API #6
  app/Http/Controllers/TarefaController.php
  app/Models/Tarefa.php
  app/Providers/AppServiceProvider.php
  app/Services/TarefaService.php
  composer.json
  composer.lock
  issue_template.md
  resources/views/index.blade.php
  routes/web.php
Labels: enhancement

#16 Criar uma lista para as tarefas #4
  app/Http/Controllers/TarefaController.php
  app/Http/Requests/TarefaFormRequest.php
  app/Models/Tarefa.php
  app/Services/TarefaService.php
  resources/views/create.blade.php
  resources/views/index.blade.php
  routes/web.php
Labels: enhancement

#19 Criar componentes de layout #18
  public/css/styles.css
  resources/views/create.blade.php
  resources/views/index.blade.php
  resources/views/layouts/main.blade.php
Labels: enhancement

#20 ci: aplicação dockerizada
  .dockerignore
  Dockerfile
  docker-compose.yml
  docker/nginx/laravel.conf
  docker/php/custom.ini
Labels: integration
